const Map<String, String> YOUTUBE_CHANNELS = {
  'UCwXdFgeE9KYzlDdR7TG9cMw': 'Flutter',
  'UCJm7i4g4z7ZGcJA_HKHLCVw': 'The Flutter Way',
  'UCFTM1FGjZSkoSPDZgtbp7hA': 'mtechviral',
  'UCSIvrn68cUk8CS8MbtBmBkA': 'Reso Coder',
  'UC6Dy0rQ6zDnQuHQ1EeErGUA': 'Marcus Ng',
  'UCjBxAm226XZvgrkO-JyjJgQ': 'Raja Yogan',
  'UC2d0BYlqQCdF9lJfydl_02Q': 'FilledStacks',
  'UCW2ATgwtNrsBrE-piE2TIrA': 'RetroPortal Studios',
  'UC3wqIkiaOUpO6EjJoCwH6_Q': 'Techie Blossom',
  'UCSLIg5O0JiYO1i2nD4RclaQ': 'Robert Brunhage',
  'UCrTnsT4OYZ53l0QGKqLeD5Q': 'Code With Andrea',
  'UCU8Mj6LLoNBXqqeoOD64tFg': 'Fun with Flutter',
  'UCNUzIz3TsiHSbgn_66kLIww': 'Flutter Community',
  'UCDCFIqDZ1QUqivxVFQDxS0w': 'whatsupcoders',
  'UCQ00Ywz-ygK-yHzKluEsABA': 'CodeX',
  'UCOoJkGYV00nr3EpZOUeuN1Q': 'Flutter Europe',
  'UCNaJHBXsvbfkItVMNmzmTPQ': 'Tadas Petra',
  'UCCkjYARLbR1ws4_lMuvJ2vg': 'Doctor Code',
  'UCgUnLn1FpuHHmO66vn4o1NA': 'Flutter Explained',
  'UCRCpzcQz-t2ueVihCIx5jDg': 'Nick Manning',
  'UCplT2lzN6MHlVHHLt6so39A': 'Flutterando',
  'UC0s92eMIsyR9otmIiY4v8Ww': 'Erico Darmawan Handoyo',
  'UC0FD2apauvegCcsvqIBceLA': 'Johannes Milke',
  'UChMjpXwPFzK6x82qz-R_TEQ': 'Learn Flutter Code',
  'UCQ5EaVUK-cZxQL2AdOCG6Pg': 'Snippet Coder',
  'UCDop5l09jz_ExPaQwGL-RrQ': 'the growing developer',
  'UC4hWRtPpBaq72ERUuKsvO7g': 'easy approach',
  'UCy4TEe4CGipnHotkBztYvng': 'Programming Addict',
  'UCSUI2lxw7Q-CrrYrIOdZhKg': 'Codes Easy',
  'UCsPdgUIoOBTBI1UmulW1pdw': 'Sanskar Tiwari',
  'UCQUfwiydQHf0u4Gb6uT-hyA': 'Abdul Aziz Ahwan',
  'UCls44vOM2YDLw1StJuLP8Eg': 'Mallu Developer',
  'UCqibwXKXYPpnPuo5xg5l2xA': 'Bram Vanbilsen',
  'UC5lbdURzjB0irr-FTbjWN1A': 'Mobile Programmer',
  'UCFi0LVUvZG8V9g7npfMGaaw': 'The CS Guy',
  'UCIHBIPape0dWHKANkivrcJw': 'Coding Cafe',
  'UCuXm84E6yWF0dIKmwvwc9sQ': 'Afgprogrammer',
  'UCHSRZk4k6e-hqIXBBM4b2iA': 'Creative Bracket',
  'UCw2IfXRCHaYryORhBICp8QA': 'SuperDeclarative!',
  'UCv75sKQFFIenWHrprnrR9aA': 'Kilo Loco',
  'UC6i0OkpJeO0qBZGTj-eiAsw': 'Codepur',
  'UCRl79zOEtiLCglAFZJJzEZQ': 'Santos',
  'UCFKZxStYsOVrzdN_FCZ0NGg': 'diegoveloper',
};
